url: "https://aryanshetty711.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Aryan Shetty" # the name of your site, e.g. ACME Corp.
description: ""

collections: 
  projects: 
    output: true
    permalink: /projects/:title
    sort_by: 'order'  # Add this line to explicitly sort by 'order'
