url: "https://eightants.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/academic-aryan" # the subpath of your site, e.g. /blog
title: "Aryan Shetty" # the name of your site, e.g. ACME Corp.
description: ""

collections: 
  projects: 
    output: true
    permalink: /projects/:title