header_title: aryan.

menu:
- {name: 'projects', url: '/projects'}
- {name: 'photography', url: '/photography'}
- {name: 'blog', href: 'https://drive.google.com/drive/folders/1NiihHS6UpGeFRC88_WU25MU7aCrhmTTu'}
- {name: 'resume', href: '/assets/resume.pdf'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}
